version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/dsp-testing/dependabot-updates-issue-10267
    username: thavaahariharangit@github.com
    password: ${{secrets.PACKAGES_PAT}}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: "daily"
